{% set version = "0.6-13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-relations
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/relations_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/relations/relations_{{ version }}.tar.gz
  sha256: f859c336fb0c4a2df7f294b33d1d04f95c6988e5e76933e2e70bf291d904d9da

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cluster
    - r-sets >=1.0_16
    - r-slam
  run:
    - r-base
    - r-cluster
    - r-sets >=1.0_16
    - r-slam

test:
  commands:
    - $R -e "library('relations')"           # [not win]
    - "\"%R%\" -e \"library('relations')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=relations
  license: GPL-2
  summary: Data structures and algorithms for k-ary relations with arbitrary domains, featuring relational algebra, predicate functions, and fitters for consensus relations.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: relations
# Version: 0.6-8
# Encoding: UTF-8
# Title: Data Structures and Algorithms for Relations
# Description: Data structures and algorithms for k-ary relations with arbitrary domains, featuring relational algebra, predicate functions, and fitters for consensus relations.
# Authors@R: c(person(given = "David", family = "Meyer", role = c("aut")), person(given = "Kurt", family = "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org", comment = c(ORCID = "0000-0003-4198-9911")), person(given = "Christian", family = "Buchta", role = "ctb"))
# LazyData: yes
# Depends: R (>= 3.2.0)
# Imports: cluster, stats, slam, sets (>= 1.0-16), graphics, grDevices
# Suggests: Rgraphviz, clue (>= 0.3-49), Rglpk (>= 0.3-1), lpSolve (>= 5.6.3), Rsymphony (>= 0.1-9), methods
# Enhances: seriation, Rcplex
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2018-04-23 04:42:52 UTC; hornik
# Author: David Meyer [aut], Kurt Hornik [aut, cre] (<https://orcid.org/0000-0003-4198-9911>), Christian Buchta [ctb]
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-04-23 09:11:24 UTC
