{% set version = "0.6-18" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-relations
  version: "{{ version|replace('-', '_') }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/relations_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/relations/relations_{{ version }}.tar.gz
  sha256: 40b1fe5d34aa507f376ebac77572f41d26408ca119d41fdf97cb0ffdc6e2ef63

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cluster
    - r-sets >=1.0_16
    - r-slam
  run:
    - r-base
    - r-cluster
    - r-sets >=1.0_16
    - r-slam

test:
  commands:
    - $R -e "library('relations')"           # [not win]
    - "\"%R%\" -e \"library('relations')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=relations
  license: GPL-2.0-only
  summary: Data structures and algorithms for k-ary relations with arbitrary domains, featuring relational algebra, predicate functions, and fitters for consensus relations.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
