travis:
  secure:
    BINSTAR_TOKEN: GgwpBPrvO0Bu3Y3hdFCCN3DWIQCPnFBl7Nzi0DoTn/MkvwQMHkw25pBUlanyXqZ+NovlZ5yC96RgYNQfuk+lIQXEw8WVOk6A40pji4X5ITRJxgUgyI/gNZyQsouhqY7kTPTXas6FGYQeycdlp+7NBnt8bcBNSHawrKfZUjoIoa3HxwEHtARzre5rLAQGLs47YXybKNJyta4gYXDUqgiU0oCkSdaphxcSuYVoQSvQk9S1+4W5LiPrVWJobu9rigybIhH67+MhmxANQyHWEpXMbFTJzHSFh8kRSQG4nyKNv68/JwF9qCaSnQgSQ/iKd9jaQ7zLqpvvhift7NRw/UClFo/Y17zdcu29LC01pVE4LgaJ/6a01imqEJAq2g35VxgSPrJt1vorFMtGHwAdle2qSRtRocbXlitm6eW9GaSykEjgrjvCNLL3ZAoJXSyTIxxzVwclIq4YnIPINlPJA9bIwzMdVqy1UCPl3o0POh/9FBBdNZt1vLtyNeQCxe1D8mGPfZ6cJEmehZo+fqz/ZqfjRZWFOLO/uRkGQgPlKHcJUtiefxiQwAf+pdwB/BGbel7fzfTbl73We/VC6soxUnEcturlJJaZHj9r0zBodGxAoGMytgoyQx1Sr6awdOstjPvOb5tYt/DqNoP7bZLIQMfL7ls2a0JFYuevu18n6NokaJQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
