travis:
  secure:
    BINSTAR_TOKEN: K9TgKTyaEfdvS4fwHRkjJ4MG2Rhl2NWeWvdOvuvRh1x3pJibapJmU62lBNGR4GETNnVRwWDVpJsH3Bsn023Tp2Ar3+iWYcHtJYjvu1L0Q7WvFU6+DzEDoEOVOs9ftMoui4sOASY5wfAtrOW9RlhbwtxJBXzdX5Zif/DDwfZsCl3PaHRuBW2WekT0tVDQN+tzaA+dM4JbRb/oYZNLDyDCCu/a9q4GVdjce0/WLmudEtjZJhc7xWJPiI7Q6KZGxYyMHUFkU57DxcOBELMnFXH0a6qxcREIqNhYpffBO23R/WR2UqBtc4+P0asumWCnIKmeBCmjpUwtr185T56cJ5A9AzDiGLy9n/rwExKxTmNZGiBb57t1/6Xhx5zqXxpDSMH+oVUo109i5tXOMwi92dQnN2fZPV76M2PAH4+DAYmzpo2YhiLx2bPBrXDjbaCQJ9z6UvpjMEaI8CFbPd5LXE8/Y/hVRNP/TLijrKkW9dlJlyngMd8BTpDGIMuamwlcjrilRFVxvAcAehDcA2j2MsaoXITBgx4lxPjkjEi4nAbVX8iyEyssSWXgfLVyveal1BBZo64MSKfXoajhx3xPCqTzdtODtJOB3gM0emWLQoiFzgXmCtrwt6ng0MM41RUhhrt7nEXpD9KQL3JWJfFYALi+RteeJzfN3cwSQEb8LSzVzdY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
